// Code generated by the multiversx-sc build system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                            5
// Async Callback (empty):               1
// Total number of exported functions:   7

#![no_std]

multiversx_sc_wasm_adapter::allocator!();
multiversx_sc_wasm_adapter::panic_handler!();

multiversx_sc_wasm_adapter::endpoints! {
    decentralized_auction
    (
        init => init
        getDeadline => deadline
        getHighestBidder => highest_bidder
        getHighestBid => highest_bid
        bid => bid
        end_auction => end_auction
    )
}

multiversx_sc_wasm_adapter::async_callback_empty! {}
